Source Code Installer 2. udgave

diff --git a/sourcecodeInstaller b/sourcecodeInstaller
--- a/sourcecodeInstaller
+++ b/sourcecodeInstaller
@@ -16,55 +16,15 @@ echo
 #Asking user to choose package source
 
 tput sgr0
-#Prompting for direkt link
-echo Please input direkt link to package[Enter]
 read directLink
 export directLink
 
-perm=$(stat -c %A /usr/local/src | cut -b 9)
-
-if [ $perm = "-" ]; then
-	priviligeChanged=1
-	echo -e "${CYAN}Missing write privilege for /usr/local/src"
-	echo 'setting up permission'
-	chmod o+w /usr/local/src
-	tput sgr0
-fi  
-
-
-
-MatchingPkg=$(dpkg-query -l $pkgNm) #query installed packages
-exitCode=$? #checking exitcode to see if package is known, exit code 0 is for good query
-#echo $exitCode
-#echo $MatchingPkg
-echo
-if [ $exitCode = 0 ]; then
-  isInstalled=$(echo $MatchingPkg | grep ii -o -w| wc -w)
-  #echo $isInstalled
-  if [ $isInstalled -eq 0 ]; then
-    echo -e "${CYAN}package recognised, and it is not yet installed"
-  else
-    echo -e "${RED}package already installed"
-    exit 0
-  fi
-else
-  echo -e "${CYAN}Unknown package... ... ..." 
-fi
-export pkgNm
-echo  -e "${CYAN}proceeding with installation"
-echo 
-echo
-tput sgr0
-  else
-    echo -e "${RED}bad input"
-tput sgr0
-  fi
-done
-
-
+echo $directLink
+wget $directLink -P /usr/local/src
 
 #Decompress the downloaded tarball
 echo  -e "${CYAN}Decompressing the downloaded tarball.."
+tput sgr0
 bzip2 -cd <PACKAGE_NAME>.tar.bz2
 
 
@@ -74,11 +34,23 @@ cd usr/local/src/<PACKAGE_NAME>
 
 #Configure the build system
 echo  -e "${CYAN}configure: creating ./config.status.."
+tput sgr0
 ./configure
  
 #Build package
-echo  -e "${CYAN}Building package.."
+echo  "$Building package.."
+tput sgr0
 make
+
+echo $make
+exitCode=$?
+
+if [ $exitCode = "0" ]; then #make succesfull
+	echo "Build was successfull! Proceeding.."
+	tput sgr0
+elif [ $exitCode = "1" ]; then #make failed
+	echo -e "${RED}Something went wrong, trying to sovle dependencies"
+
 
 #Become a privileged user for system-wide install
 su root
@@ -86,9 +58,21 @@ su root
 
 #Install package
 echo  -e "${CYAN}Installing the package.."
+tput sgr0
 make install
 
+echo $make
+exitCode=$?
 
-echo  -e "${CYAN}Package installed!"
+if [ $exitCode = "0" ]; then #make install succesfull
+	echo  "Package installed!"
+	tput sgr0
+elif [ $exitCode = "1" ]; then #make install failed
+	echo -e "${RED}Something went wrong, installation failed"
+	tput sgr0
+fi
+
+
+
 
 
